# Generated by Django 6.0.2 on 2026-03-02 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mashq', models.CharField(choices=[('m1', 'Mashq 1 – Applikatsiya turlari'), ('m2', 'Mashq 2 – Origami shakllari'), ('m3', 'Mashq 3 – Kasblar'), ('m4', 'Mashq 4 – Hunarlar'), ('m5', 'Mashq 5 – Ish qurollari'), ('m6b', 'Mashq 6 – Applikatsiya test'), ('m7b', 'Mashq 7 – Origami test'), ('m8b', 'Mashq 8 – Fetr test'), ('m9b', 'Mashq 9 – Kvilling test'), ('m10b', 'Mashq 10 – Plastilin test')], max_length=10, verbose_name='Mashq')),
                ('score', models.IntegerField(default=0, verbose_name='Ball')),
                ('total', models.IntegerField(default=0, verbose_name='Jami')),
                ('is_passed', models.BooleanField(default=False, verbose_name="O'tdimi?")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
