# Generated by Django 5.2.14 on 2026-07-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_result_mashq_alter_result_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('oquvchi', "O'quvchi"), ('talaba', "O'qituvchi")], default='oquvchi', max_length=10, verbose_name='Rol'),
        ),
    ]
