# Generated by Django 5.2.14 on 2026-07-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('metodika', 'Metodika'), ('maqola', 'Maqola'), ('topshiriq', 'Topshiriq'), ('xarita', 'Instruksion texnologik xarita'), ('ishlanma', 'Dars ishlanmalar')], max_length=20, verbose_name="Bo'lim")),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('summary', models.TextField(blank=True, help_text="Ro'yxatda sarlavha ostida ko'rinadi. 1–3 gap yetarli.", verbose_name='Qisqacha tavsif')),
                ('body', models.TextField(blank=True, help_text="Ixtiyoriy. Har bir bo'sh qator yangi xatboshi bo'ladi.", verbose_name="To'liq matn")),
                ('file', models.FileField(blank=True, help_text="PDF, Word yoki taqdimot. Yuklansa, 'Yuklab olish' tugmasi chiqadi.", null=True, upload_to='materiallar/', verbose_name='Fayl')),
                ('link', models.URLField(blank=True, help_text='Ixtiyoriy: tashqi manba (masalan, jurnal sayti) havolasi.', verbose_name='Havola')),
                ('manba', models.CharField(blank=True, help_text='Masalan: jurnal nomi, nashr yili, sinf yoki mavzu.', max_length=250, verbose_name='Manba')),
                ('order', models.IntegerField(default=0, help_text='Kichik raqam yuqorida turadi.', verbose_name='Tartib')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
