# Generated by Django 5.2.14 on 2026-07-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='muqova',
            field=models.FileField(blank=True, help_text="Ixtiyoriy (JPG yoki PNG). Ro'yxatda kitob muqovasi bo'lib ko'rinadi. Bo'sh qoldirilsa, o'rniga fayl turi nishoni chiqadi.", null=True, upload_to='materiallar/muqova/', verbose_name='Muqova rasmi'),
        ),
    ]
