# Generated by Django 5.2.14 on 2026-07-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_material_muqova'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='koruv',
            field=models.FileField(blank=True, help_text="Fayl Word bo'lsa, uning PDF nusxasini shu yerga yuklang — sahifada 'Ko'rish' tugmasi paydo bo'ladi. Fayl PDF bo'lsa, bo'sh qoldiring.", null=True, upload_to='materiallar/koruv/', verbose_name="Ko'rish uchun PDF"),
        ),
    ]
