# Generated by Django 5.2.14 on 2026-08-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_material_koruv'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='kichik_bolim',
            field=models.CharField(blank=True, choices=[('rasmli_test', 'Rasmli test'), ('diktant', 'Texnologik diktantlar')], help_text='Faqat "Topshiriq" bo\'limi uchun: material qaysi ochiladigan ro\'yxatga tushishi. Boshqa bo\'limlarda bo\'sh qoldiring.', max_length=20, verbose_name="Kichik bo'lim"),
        ),
    ]
